import { create } from "zustand"
import { persist } from "zustand/middleware"

// Types
export interface Event {
  id: string
  title: string
  date: string
  venue: string
  status: "pending" | "confirmed" | "cancelled"
  type: "propio" | "privado" | "feriado"
  description?: string
  theme?: string
  emoji?: string
  budget?: number
  attendees?: number
  address?: string
  openingTime?: string
  closingTime?: string
  setupStartTime?: string
  teardownTime?: string
  loadingPoint?: string
  producerContact?: {
    name: string
    phone: string
    email: string
  }
  hasLocalPermit?: boolean
  hasAlcoholPermit?: boolean
  notes?: string
  providers?: any[]
  venueId?: string
}

export interface Venue {
  id: string
  nombre: string
  location: string
  capacity: number
  type: "club" | "salon" | "outdoor" | "teatro"
  contact: string
  rating: number
}

export interface Provider {
  id: string
  name: string
  category: string
  contact: string
  rating?: number
  services: string[]
  priceRange: string
  item?: string
  price?: string
  paymentMethod?: string
  status?: string
  staff?: string
  insurance?: string
  deadline?: string
  observations?: string
  blocked?: boolean
  blockReason?: string
}

export interface Task {
  id: string
  title: string
  description: string
  status: "pending" | "in-progress" | "completed"
  priority: "low" | "medium" | "high"
  assignee: string // Cambiar de assignedTo a assignee para consistencia
  dueDate: string
  eventId?: string
  category: string
  isAutomated?: boolean
  automatedTaskType?: "pasajes" | "hoteleria" | "aduana_ida" | "aduana_vuelta"
  daysUntilEvent?: number
  createdAt?: string
  updatedAt?: string
}

export interface Contract {
  id: string
  type: "bailarin" | "tecnico"
  name: string
  email: string
  phone: string
  rate: number
  status: "active" | "inactive" | "draft" | "sent" | "signed"
  startDate: string
  endDate?: string
  skills: string[]
  eventIds: string[]
  providerName?: string
  contractorName?: string
  amount?: number
  date?: string
}

export interface BudgetItem {
  id: string
  area: string
  item: string
  cantidad: number
  precioUnitario: number
  precioTotal: number
  resultadoNegociacion: number
  desviacion?: number
  status: "pending" | "approved" | "paid"
  vendor?: string
  eventId: string
  category?: string
  description?: string
  estimatedCost?: number
  actualCost?: number
}

export interface ChatMessage {
  id: string
  content: string
  message: string
  sender: string
  timestamp: string
  type: "text" | "file" | "image"
  eventId?: string
}

export interface Chat {
  id: string
  name: string
  participants: string[]
  messages: ChatMessage[]
  lastMessage?: string
  lastActivity: string
  eventId?: string
}

interface UnifiedEventStore {
  // State
  events: Event[]
  venues: Venue[]
  providers: Provider[]
  tasks: Task[]
  contracts: Contract[]
  budgetItems: BudgetItem[]
  chats: Chat[]
  chatMessages: ChatMessage[]

  // Event actions
  addEvent: (event: Event) => void
  updateEvent: (id: string, event: Partial<Event>) => void
  deleteEvent: (id: string) => void
  getEvent: (id: string) => Event | undefined

  // Venue actions
  addVenue: (venue: Venue) => void
  updateVenue: (id: string, venue: Partial<Venue>) => void
  deleteVenue: (id: string) => void
  getVenue: (id: string) => Venue | undefined

  // Provider actions
  addProvider: (provider: Partial<Provider>) => void
  updateProvider: (id: string, provider: Partial<Provider>) => void
  deleteProvider: (id: string) => void
  getProvider: (id: string) => Provider | undefined
  rateProvider: (id: string, rating: number) => void
  blockProvider: (id: string, reason: string) => void

  // Task actions
  addTask: (task: Task) => void
  updateTask: (id: string, task: Partial<Task>) => void
  deleteTask: (id: string) => void
  getTask: (id: string) => Task | undefined

  // Contract actions
  addContract: (contract: Contract) => void
  updateContract: (id: string, contract: Partial<Contract>) => void
  deleteContract: (id: string) => void
  getContract: (id: string) => Contract | undefined

  // Budget actions
  addBudgetItem: (item: BudgetItem) => void
  updateBudgetItem: (id: string, item: Partial<BudgetItem>) => void
  deleteBudgetItem: (id: string) => void
  getBudgetItem: (id: string) => BudgetItem | undefined

  // Chat actions
  addChat: (chat: Chat) => void
  updateChat: (id: string, chat: Partial<Chat>) => void
  deleteChat: (id: string) => void
  getChat: (id: string) => Chat | undefined
  addMessage: (chatId: string, message: ChatMessage) => void
}

// EVENTOS CORREGIDOS 2025 - FECHAS REALES CONFIRMADAS (SIN ELECCIONES)
const eventosCompletos2025: Event[] = [
  // ENERO 2025 - CONFIRMADOS
  {
    id: "event-2025-01-11",
    title: "Stadium",
    date: "2025-01-11",
    venue: "Stadium",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Stadium",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-01-19",
    title: "Seasons",
    date: "2025-01-19",
    venue: "Seasons",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Seasons",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-01-25",
    title: "Oasis",
    date: "2025-01-25",
    venue: "Oasis",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Oasis",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },

  // FEBRERO 2025 - CONFIRMADOS
  {
    id: "event-2025-02-02",
    title: "Normandina",
    date: "2025-02-02",
    venue: "Normandina",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Normandina",
    theme: "sueño",
    emoji: "🌙",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-02-15",
    title: "Wasabi",
    date: "2025-02-15",
    venue: "Wasabi",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Wasabi",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-02-16",
    title: "Seasons",
    date: "2025-02-16",
    venue: "Seasons",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Seasons",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-02-22",
    title: "Cuenca",
    date: "2025-02-22",
    venue: "Cuenca",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Cuenca",
    theme: "general",
    emoji: "🎵",
    address: "Cuenca, Ecuador",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-02-23",
    title: "Quito",
    date: "2025-02-23",
    venue: "Quito",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Quito",
    theme: "general",
    emoji: "🎵",
    address: "Quito, Ecuador",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  // EVENTOS SEPARADOS - 1 de marzo
  {
    id: "event-2025-03-01-amk",
    title: "AMK",
    date: "2025-03-01",
    venue: "Amerika",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - AMK",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-03-01-rosario",
    title: "Rosario",
    date: "2025-03-01",
    venue: "Rosario",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Rosario",
    theme: "general",
    emoji: "🎵",
    address: "Rosario, Santa Fe",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },

  // MARZO 2025 - CONFIRMADOS
  {
    id: "event-2025-03-03",
    title: "Gap",
    date: "2025-03-03",
    venue: "Gap",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Gap",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-03-08",
    title: "Auditorio Sur",
    date: "2025-03-08",
    venue: "Auditorio Sur",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Auditorio Sur",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-03-15",
    title: "Seasons",
    date: "2025-03-15",
    venue: "Seasons",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Seasons",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-03-16",
    title: "Asunción",
    date: "2025-03-16",
    venue: "Asunción",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Asunción",
    theme: "bosque",
    emoji: "🍄",
    address: "Asunción, Paraguay",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-03-23",
    title: "Córdoba",
    date: "2025-03-23",
    venue: "Córdoba",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Córdoba",
    theme: "general",
    emoji: "🎵",
    address: "Córdoba, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-03-24",
    title: "Lolla",
    date: "2025-03-24",
    venue: "Lollapalooza",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Lollapalooza",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "12:00",
    closingTime: "23:00",
    setupStartTime: "08:00",
    teardownTime: "02:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-03-29",
    title: "Oasis",
    date: "2025-03-29",
    venue: "Oasis",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Oasis",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },

  // ABRIL 2025 - CONFIRMADOS
  {
    id: "event-2025-04-12",
    title: "Rosario",
    date: "2025-04-12",
    venue: "Rosario",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Rosario",
    theme: "general",
    emoji: "🎵",
    address: "Rosario, Santa Fe",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-04-19",
    title: "AMK",
    date: "2025-04-19",
    venue: "Amerika",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - AMK",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  // EVENTOS SEPARADOS - 20 de abril
  {
    id: "event-2025-04-20-montevideo",
    title: "Montevideo",
    date: "2025-04-20",
    venue: "Montevideo",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Montevideo",
    theme: "general",
    emoji: "🎵",
    address: "Montevideo, Uruguay",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-04-20-hipodromo",
    title: "Hipódromo San Isidro",
    date: "2025-04-20",
    venue: "Hipódromo San Isidro",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Hipódromo San Isidro",
    theme: "general",
    emoji: "🎵",
    address: "San Isidro, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  // EVENTOS SEPARADOS - 26 de abril
  {
    id: "event-2025-04-26-auditorio-oeste",
    title: "Auditorio Oeste",
    date: "2025-04-26",
    venue: "Auditorio Oeste",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Auditorio Oeste",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-04-26-wasabi",
    title: "Wasabi",
    date: "2025-04-26",
    venue: "Wasabi",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Wasabi",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },

  // MAYO 2025 - CONFIRMADOS
  {
    id: "event-2025-05-03",
    title: "La Plata",
    date: "2025-05-03",
    venue: "La Plata",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - La Plata",
    theme: "general",
    emoji: "🎵",
    address: "La Plata, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-05-11",
    title: "Quilmes",
    date: "2025-05-11",
    venue: "Quilmes",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Quilmes",
    theme: "general",
    emoji: "🎵",
    address: "Quilmes, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-05-17",
    title: "AMK",
    date: "2025-05-17",
    venue: "Amerika",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - AMK",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  // EVENTOS SEPARADOS - 24 de mayo
  {
    id: "event-2025-05-24-mendoza",
    title: "Mendoza",
    date: "2025-05-24",
    venue: "Mendoza",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Mendoza",
    theme: "general",
    emoji: "🎵",
    address: "Mendoza, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-05-24-laplata",
    title: "La Plata",
    date: "2025-05-24",
    venue: "La Plata",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - La Plata",
    theme: "general",
    emoji: "🎵",
    address: "La Plata, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-05-25",
    title: "Mendoza",
    date: "2025-05-25",
    venue: "Mendoza",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Mendoza",
    theme: "general",
    emoji: "🎵",
    address: "Mendoza, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },

  // JUNIO 2025 - CONFIRMADOS
  {
    id: "event-2025-06-08",
    title: "Guayaquil",
    date: "2025-06-08",
    venue: "Guayaquil",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Guayaquil",
    theme: "general",
    emoji: "🎵",
    address: "Guayaquil, Ecuador",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-06-14",
    title: "AMK",
    date: "2025-06-14",
    venue: "Amerika",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - AMK",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-06-15",
    title: "Córdoba",
    date: "2025-06-15",
    venue: "Córdoba",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Córdoba",
    theme: "general",
    emoji: "🎵",
    address: "Córdoba, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-06-21",
    title: "MDQ",
    date: "2025-06-21",
    venue: "Mar del Plata",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Mar del Plata",
    theme: "general",
    emoji: "🎵",
    address: "Mar del Plata, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },

  // JULIO 2025 - CONFIRMADOS
  {
    id: "event-2025-07-05",
    title: "The Bow",
    date: "2025-07-05",
    venue: "The Bow",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - The Bow",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-07-09",
    title: "Forest Dan (Tortuguitas)",
    date: "2025-07-09",
    venue: "Forest Dan",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Forest Dan (Tortuguitas)",
    theme: "bosque",
    emoji: "🍄",
    address: "Tortuguitas, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  // EVENTOS SEPARADOS - 20 de julio
  {
    id: "event-2025-07-20-auditorio-oeste",
    title: "Auditorio Oeste",
    date: "2025-07-20",
    venue: "Auditorio Oeste",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - Auditorio Oeste",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-07-20-mdq-msm",
    title: "MDQ MSM",
    date: "2025-07-20",
    venue: "Mar del Plata",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - MDQ MSM",
    theme: "general",
    emoji: "🎵",
    address: "Mar del Plata, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },
  {
    id: "event-2025-07-26",
    title: "AMK",
    date: "2025-07-26",
    venue: "Amerika",
    status: "confirmed",
    type: "propio",
    description: "Evento propio - AMK",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: true,
    hasAlcoholPermit: true,
    providers: [],
  },

  // DESDE AQUÍ TODOS PENDIENTES (30 JULIO EN ADELANTE - FECHA CORTE REAL)
  // AGOSTO 2025 - PENDIENTES
  // EVENTOS SEPARADOS - 9 de agosto
  {
    id: "event-2025-08-09-auditorio-sur",
    title: "Auditorio Sur",
    date: "2025-08-09",
    venue: "Auditorio Sur",
    status: "pending",
    type: "propio",
    description: "Evento propio - Auditorio Sur",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-08-09-rosario",
    title: "Rosario",
    date: "2025-08-09",
    venue: "Rosario",
    status: "pending",
    type: "propio",
    description: "Evento propio - Rosario",
    theme: "general",
    emoji: "🎵",
    address: "Rosario, Santa Fe",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-08-16",
    title: "Medusa",
    date: "2025-08-16",
    venue: "Medusa",
    status: "pending",
    type: "propio",
    description: "Evento propio - Medusa",
    theme: "ia",
    emoji: "🧬",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-08-17",
    title: "Montevideo",
    date: "2025-08-17",
    venue: "Montevideo",
    status: "pending",
    type: "propio",
    description: "Evento propio - Montevideo",
    theme: "general",
    emoji: "🎵",
    address: "Montevideo, Uruguay",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-08-23",
    title: "AMK",
    date: "2025-08-23",
    venue: "Amerika",
    status: "pending",
    type: "propio",
    description: "Evento propio - AMK",
    theme: "ia",
    emoji: "🧬",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-08-30",
    title: "Wasabi",
    date: "2025-08-30",
    venue: "Wasabi",
    status: "pending",
    type: "propio",
    description: "Evento propio - Wasabi",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-08-31",
    title: "Native Beach Club Cardales",
    date: "2025-08-31",
    venue: "Native Beach Club",
    status: "pending",
    type: "propio",
    description: "Evento propio - Native Beach Club Cardales",
    theme: "pirata",
    emoji: "🏴‍☠️",
    address: "Cardales, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },

  // SEPTIEMBRE 2025 - PENDIENTES
  {
    id: "event-2025-09-06",
    title: "Mendoza",
    date: "2025-09-06",
    venue: "Mendoza",
    status: "pending",
    type: "propio",
    description: "Evento propio - Mendoza",
    theme: "shanghai",
    emoji: "🐲",
    address: "Mendoza, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-09-07",
    title: "Santa Fe",
    date: "2025-09-07",
    venue: "Santa Fe",
    status: "pending",
    type: "propio",
    description: "Evento propio - Santa Fe",
    theme: "muertos",
    emoji: "💀",
    address: "Santa Fe, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  // EVENTOS SEPARADOS - 14 de septiembre
  {
    id: "event-2025-09-14-cordoba",
    title: "Córdoba",
    date: "2025-09-14",
    venue: "Córdoba",
    status: "pending",
    type: "propio",
    description: "Evento propio - Córdoba",
    theme: "shanghai",
    emoji: "🐲",
    address: "Córdoba, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-09-14-asuncion",
    title: "Asunción",
    date: "2025-09-14",
    venue: "Asunción",
    status: "pending",
    type: "propio",
    description: "Evento propio - Asunción",
    theme: "bosque",
    emoji: "🍄",
    address: "Asunción, Paraguay",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-09-20",
    title: "AMK",
    date: "2025-09-20",
    venue: "Amerika",
    status: "pending",
    type: "propio",
    description: "Evento propio - AMK",
    theme: "bosque",
    emoji: "🍄",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-09-21",
    title: "Quilmes",
    date: "2025-09-21",
    venue: "Quilmes",
    status: "pending",
    type: "propio",
    description: "Evento propio - Quilmes",
    theme: "bosque",
    emoji: "🍄",
    address: "Quilmes, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-09-28",
    title: "Forest Dan",
    date: "2025-09-28",
    venue: "Forest Dan",
    status: "pending",
    type: "propio",
    description: "Evento propio - Forest Dan",
    theme: "bosque",
    emoji: "🍄",
    address: "Tortuguitas, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },

  // OCTUBRE 2025 - PENDIENTES
  {
    id: "event-2025-10-05",
    title: "Bahía Blanca",
    date: "2025-10-05",
    venue: "Bahía Blanca",
    status: "pending",
    type: "propio",
    description: "Evento propio - Bahía Blanca",
    theme: "muertos",
    emoji: "💀",
    address: "Bahía Blanca, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-10-11",
    title: "AMK",
    date: "2025-10-11",
    venue: "Amerika",
    status: "pending",
    type: "propio",
    description: "Evento propio - AMK",
    theme: "sueño",
    emoji: "🌙",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-10-13",
    title: "MDQ",
    date: "2025-10-13",
    venue: "Mar del Plata",
    status: "pending",
    type: "propio",
    description: "Evento propio - MDQ",
    theme: "muertos",
    emoji: "💀",
    address: "Mar del Plata, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-10-19",
    title: "Carlos Casares",
    date: "2025-10-19",
    venue: "Carlos Casares",
    status: "pending",
    type: "propio",
    description: "Evento propio - Carlos Casares",
    theme: "muertos",
    emoji: "💀",
    address: "Carlos Casares, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-10-25",
    title: "Meter Fecha",
    date: "2025-10-25",
    venue: "",
    status: "pending",
    type: "propio",
    description: "Evento propio - Meter Fecha",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  // EVENTOS SEPARADOS - 1 de noviembre
  {
    id: "event-2025-11-01-amk",
    title: "AMK",
    date: "2025-11-01",
    venue: "Amerika",
    status: "pending",
    type: "propio",
    description: "Evento propio - AMK Halloween",
    theme: "muertos",
    emoji: "💀",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-11-01-medusa",
    title: "Medusa",
    date: "2025-11-01",
    venue: "Medusa",
    status: "pending",
    type: "propio",
    description: "Evento propio - Medusa Halloween",
    theme: "ia",
    emoji: "🧬",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },

  // NOVIEMBRE 2025 - PENDIENTES
  {
    id: "event-2025-11-02",
    title: "Evento Privado FD",
    date: "2025-11-02",
    venue: "Forest Dan",
    status: "pending",
    type: "privado",
    description: "Evento privado - Forest Dan",
    theme: "general",
    emoji: "",
    address: "Tortuguitas, Buenos Aires",
    openingTime: "20:00",
    closingTime: "04:00",
    setupStartTime: "16:00",
    teardownTime: "06:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-11-08",
    title: "Fecha Au Sur",
    date: "2025-11-08",
    venue: "Auditorio Sur",
    status: "pending",
    type: "propio",
    description: "Evento propio - Auditorio Sur",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-11-09",
    title: "Estancia Shibumi",
    date: "2025-11-09",
    venue: "Estancia Shibumi",
    status: "pending",
    type: "propio",
    description: "Evento propio - Estancia Shibumi",
    theme: "muertos",
    emoji: "💀",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-11-15",
    title: "Rosario",
    date: "2025-11-15",
    venue: "Rosario",
    status: "pending",
    type: "propio",
    description: "Evento propio - Rosario",
    theme: "muertos",
    emoji: "💀",
    address: "Rosario, Santa Fe",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-11-16",
    title: "Au. Oeste",
    date: "2025-11-16",
    venue: "Auditorio Oeste",
    status: "pending",
    type: "propio",
    description: "Evento propio - Auditorio Oeste",
    theme: "sueño",
    emoji: "🌙",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-11-23",
    title: "Evento Privado ECDLS",
    date: "2025-11-23",
    venue: "",
    status: "pending",
    type: "privado",
    description: "Evento privado - ECDLS",
    theme: "general",
    emoji: "",
    address: "Buenos Aires, Argentina",
    openingTime: "20:00",
    closingTime: "04:00",
    setupStartTime: "16:00",
    teardownTime: "06:00",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-11-24",
    title: "Normandina",
    date: "2025-11-24",
    venue: "Normandina",
    status: "pending",
    type: "propio",
    description: "Evento propio - Normandina",
    theme: "sueño",
    emoji: "🌙",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-11-29",
    title: "Wasabi",
    date: "2025-11-29",
    venue: "Wasabi",
    status: "pending",
    type: "propio",
    description: "Evento propio - Wasabi",
    theme: "general",
    emoji: "🎵",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },

  // DICIEMBRE 2025 - PENDIENTES
  {
    id: "event-2025-12-06",
    title: "AMK",
    date: "2025-12-06",
    venue: "Amerika",
    status: "pending",
    type: "propio",
    description: "Evento propio - AMK",
    theme: "sueño",
    emoji: "🌙",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-12-13",
    title: "Auditorio Sur",
    date: "2025-12-13",
    venue: "Auditorio Sur",
    status: "pending",
    type: "propio",
    description: "Evento propio - Auditorio Sur",
    theme: "sueño",
    emoji: "🌙",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-12-14",
    title: "Córdoba",
    date: "2025-12-14",
    venue: "Córdoba",
    status: "pending",
    type: "propio",
    description: "Evento propio - Córdoba",
    theme: "muertos",
    emoji: "💀",
    address: "Córdoba, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-12-20",
    title: "Medusa",
    date: "2025-12-20",
    venue: "Medusa",
    status: "pending",
    type: "propio",
    description: "Evento propio - Medusa",
    theme: "ia",
    emoji: "🧬",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  // EVENTOS SEPARADOS - 21 de diciembre
  {
    id: "event-2025-12-21-montevideo",
    title: "Montevideo",
    date: "2025-12-21",
    venue: "Montevideo",
    status: "pending",
    type: "propio",
    description: "Evento propio - Montevideo",
    theme: "muertos",
    emoji: "💀",
    address: "Montevideo, Uruguay",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-12-21-forest-dan",
    title: "Forest Dan",
    date: "2025-12-21",
    venue: "Forest Dan",
    status: "pending",
    type: "propio",
    description: "Evento propio - Forest Dan",
    theme: "sueño",
    emoji: "🌙",
    address: "Tortuguitas, Buenos Aires",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  // EVENTOS SEPARADOS - 27 de diciembre
  {
    id: "event-2025-12-27-amk",
    title: "AMK",
    date: "2025-12-27",
    venue: "Amerika",
    status: "pending",
    type: "propio",
    description: "Evento propio - AMK",
    theme: "shanghai",
    emoji: "🐲",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "event-2025-12-27-oasis",
    title: "Oasis",
    date: "2025-12-27",
    venue: "Oasis",
    status: "pending",
    type: "propio",
    description: "Evento propio - Oasis",
    theme: "shanghai",
    emoji: "🐲",
    address: "Buenos Aires, Argentina",
    openingTime: "00:30",
    closingTime: "06:00",
    setupStartTime: "18:00",
    teardownTime: "08:00",
    loadingPoint: "Entrada principal",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },

  // FERIADOS OFICIALES 2025 - SEGÚN CALENDARIO GUBERNAMENTAL
  {
    id: "feriado-2025-01-01",
    title: "Año Nuevo",
    date: "2025-01-01",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado inamovible - Año Nuevo",
    theme: "año_nuevo",
    emoji: "🎉",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-02-01",
    title: "Día no laborable",
    date: "2025-02-01",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Día no laborable",
    theme: "general",
    emoji: "📅",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-03-03",
    title: "Carnaval",
    date: "2025-03-03",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado - Carnaval",
    theme: "general",
    emoji: "🎭",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-03-04",
    title: "Carnaval",
    date: "2025-03-04",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado - Carnaval",
    theme: "general",
    emoji: "🎭",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-03-24",
    title: "Día Nacional de la Memoria por la Verdad y la Justicia",
    date: "2025-03-24",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado inamovible - Día Nacional de la Memoria por la Verdad y la Justicia",
    theme: "general",
    emoji: "🇦🇷",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-03-31",
    title: "Fiesta de la Ruptura del Ayuno del Sagrado Mes de Ramadán",
    date: "2025-03-31",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Día no laborable - Fiesta de la Ruptura del Ayuno del Sagrado Mes de Ramadán (Id al-Fitr)",
    theme: "general",
    emoji: "🌙",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-04-02",
    title: "Día del Veterano y de los Caídos en la Guerra de Malvinas",
    date: "2025-04-02",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado inamovible - Día del Veterano y de los Caídos en la Guerra de Malvinas",
    theme: "general",
    emoji: "🇦🇷",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-04-13",
    title: "Primeros dos días de la Pascua Judía",
    date: "2025-04-13",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado - Primeros dos días de la Pascua Judía",
    theme: "general",
    emoji: "✡️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-04-14",
    title: "Primeros dos días de la Pascua Judía",
    date: "2025-04-14",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado - Primeros dos días de la Pascua Judía",
    theme: "general",
    emoji: "✡️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-04-17",
    title: "Jueves Santo Festividad Cristiana",
    date: "2025-04-17",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado - Jueves Santo Festividad Cristiana",
    theme: "general",
    emoji: "✝️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-04-18",
    title: "Viernes Santo Festividad Cristiana",
    date: "2025-04-18",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado - Viernes Santo Festividad Cristiana",
    theme: "general",
    emoji: "✝️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-04-19",
    title: "Últimos dos días de la Pascua Judía",
    date: "2025-04-19",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado - Últimos dos días de la Pascua Judía",
    theme: "general",
    emoji: "✡️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-04-20",
    title: "Últimos dos días de la Pascua Judía",
    date: "2025-04-20",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado - Últimos dos días de la Pascua Judía",
    theme: "general",
    emoji: "✡️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-04-24",
    title: "Día de acción por la tolerancia y el respeto entre los pueblos",
    date: "2025-04-24",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado - Día de acción por la tolerancia y el respeto entre los pueblos",
    theme: "general",
    emoji: "🕊️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-05-01",
    title: "Día del Trabajador",
    date: "2025-05-01",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado inamovible - Día del Trabajador",
    theme: "general",
    emoji: "⚒️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-05-02",
    title: "Día no laborable con fines turísticos",
    date: "2025-05-02",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Día no laborable con fines turísticos",
    theme: "general",
    emoji: "🏖️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-05-25",
    title: "Día de la Revolución de Mayo",
    date: "2025-05-25",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado inamovible - Día de la Revolución de Mayo",
    theme: "general",
    emoji: "🇦🇷",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-06-06",
    title: "Fiesta del Sacrificio",
    date: "2025-06-06",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Día no laborable - Fiesta del Sacrificio",
    theme: "general",
    emoji: "🕌",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-06-16",
    title: "Paso a la Inmortalidad del Gral. Don Martín Miguel de Güemes",
    date: "2025-06-16",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado trasladable - Paso a la Inmortalidad del Gral. Don Martín Miguel de Güemes",
    theme: "general",
    emoji: "🇦🇷",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-06-20",
    title: "Paso a la Inmortalidad del Gral. Manuel Belgrano",
    date: "2025-06-20",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado inamovible - Paso a la Inmortalidad del Gral. Manuel Belgrano",
    theme: "general",
    emoji: "🇦🇷",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-06-26",
    title: "Año Nuevo Islámico",
    date: "2025-06-26",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Día no laborable - Año Nuevo Islámico",
    theme: "general",
    emoji: "🌙",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-07-09",
    title: "Día de la Independencia",
    date: "2025-07-09",
    venue: "",
    status: "confirmed",
    type: "feriado",
    description: "Feriado inamovible - Día de la Independencia",
    theme: "general",
    emoji: "🇦🇷",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-08-15",
    title: "Día no laborable con fines turísticos",
    date: "2025-08-15",
    venue: "",
    status: "pending",
    type: "feriado",
    description: "Día no laborable con fines turísticos",
    theme: "general",
    emoji: "🏖️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-08-17",
    title: "Paso a la Inmortalidad del Gral. José de San Martín",
    date: "2025-08-17",
    venue: "",
    status: "pending",
    type: "feriado",
    description: "Feriado trasladable - Paso a la Inmortalidad del Gral. José de San Martín",
    theme: "general",
    emoji: "🇦🇷",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-09-23",
    title: "Año Nuevo Judío",
    date: "2025-09-23",
    venue: "",
    status: "pending",
    type: "feriado",
    description: "Día no laborable - Año Nuevo Judío",
    theme: "general",
    emoji: "✡️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-09-24",
    title: "Año Nuevo Judío",
    date: "2025-09-24",
    venue: "",
    status: "pending",
    type: "feriado",
    description: "Día no laborable - Año Nuevo Judío",
    theme: "general",
    emoji: "✡️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-10-02",
    title: "Día del Perdón",
    date: "2025-10-02",
    venue: "",
    status: "pending",
    type: "feriado",
    description: "Día no laborable - Día del Perdón",
    theme: "general",
    emoji: "✡️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-10-12",
    title: "Día de la Raza",
    date: "2025-10-12",
    venue: "",
    status: "pending",
    type: "feriado",
    description: "Feriado trasladable - Día de la Raza",
    theme: "general",
    emoji: "🇦🇷",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-11-21",
    title: "Día no laborable con fines turísticos",
    date: "2025-11-21",
    venue: "",
    status: "pending",
    type: "feriado",
    description: "Día no laborable con fines turísticos",
    theme: "general",
    emoji: "🏖️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-11-24",
    title: "Día de la Soberanía Nacional",
    date: "2025-11-24",
    venue: "",
    status: "pending",
    type: "feriado",
    description: "Feriado trasladable - Día de la Soberanía Nacional",
    theme: "general",
    emoji: "🇦🇷",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-12-08",
    title: "Inmaculada Concepción de María",
    date: "2025-12-08",
    venue: "",
    status: "pending",
    type: "feriado",
    description: "Feriado inamovible - Inmaculada Concepción de María",
    theme: "general",
    emoji: "✝️",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
  {
    id: "feriado-2025-12-25",
    title: "Navidad",
    date: "2025-12-25",
    venue: "",
    status: "pending",
    type: "feriado",
    description: "Feriado inamovible - Navidad",
    theme: "navidad",
    emoji: "🎄",
    address: "Argentina",
    openingTime: "00:00",
    closingTime: "23:59",
    setupStartTime: "00:00",
    teardownTime: "23:59",
    loadingPoint: "N/A",
    producerContact: {
      name: "Franco",
      phone: "+54 11 1234-5678",
      email: "franco@der.com",
    },
    hasLocalPermit: false,
    hasAlcoholPermit: false,
    providers: [],
  },
]

const initialVenues: Venue[] = [
  {
    id: "1",
    nombre: "Amerika",
    location: "GASCON 1040 - C.A.B.A.",
    capacity: 1500,
    type: "club",
    contact: "info@amerika.com.ar",
    rating: 5,
  },
  {
    id: "2",
    nombre: "Forest Dan",
    location: "Tortugas Open Mall, Ramal Pilar km 36,5, B1667 Tortuguitas, Provincia de Buenos Aires",
    capacity: 1000,
    type: "outdoor",
    contact: "info@forestdan.com",
    rating: 4,
  },
  {
    id: "3",
    nombre: "Auditorio Sur",
    location: "AV. MEEKS 1080 - TEMPERLEY - PROVINCIA DE BUENOS AIRES",
    capacity: 800,
    type: "teatro",
    contact: "info@auditoriosur.com",
    rating: 4,
  },
  {
    id: "4",
    nombre: "Seasons",
    location: "Buenos Aires, Argentina",
    capacity: 600,
    type: "club",
    contact: "info@seasons.com.ar",
    rating: 4,
  },
  {
    id: "5",
    nombre: "Medusa",
    location: "Calle 55 esq 11 - La Plata",
    capacity: 1200,
    type: "club",
    contact: "info@medusa.com.ar",
    rating: 5,
  },
  {
    id: "6",
    nombre: "Wasabi",
    location: "Buenos Aires, Argentina",
    capacity: 800,
    type: "club",
    contact: "info@wasabi.com.ar",
    rating: 4,
  },
  {
    id: "7",
    nombre: "Normandina",
    location: "AV. PATRICIO PERALTA RAMOS 5050 - MAR DEL PLATA - PROVINCIA DE BUENOS AIRES",
    capacity: 600,
    type: "club",
    contact: "info@normandina.com.ar",
    rating: 4,
  },
  {
    id: "8",
    nombre: "Oasis",
    location: "Acceso Punta Carrasco, Cdad. Autónoma de Buenos Aires",
    capacity: 1000,
    type: "club",
    contact: "info@oasis.com.ar",
    rating: 4,
  },
  {
    id: "9",
    nombre: "Auditorio Oeste",
    location: "AV. RIVADAVIA 17230 - HAEDO - PROVINCIA DE BUENOS AIRES",
    capacity: 900,
    type: "teatro",
    contact: "info@auditorioeste.com",
    rating: 4,
  },
  {
    id: "10",
    nombre: "Club Paraguay",
    location: "Av. Marcelo T. de Alvear 635, Córdoba",
    capacity: 800,
    type: "club",
    contact: "info@clubparaguay.com",
    rating: 4,
  },
  {
    id: "11",
    nombre: "Quilmes",
    location: "GARIBALDI 228, QUILMES - PROVINCIA DE BUENOS AIRES",
    capacity: 700,
    type: "club",
    contact: "info@quilmes.com",
    rating: 4,
  },
  {
    id: "12",
    nombre: "Jaguar Haus",
    location: "MARTIN RODRIGUEZ 198 - ROSARIO - SANTA FE",
    capacity: 1000,
    type: "club",
    contact: "info@jaguarhaus.com",
    rating: 4,
  },
  {
    id: "13",
    nombre: "The Bow",
    location: "Acceso Punta Carrasco, Cdad. Autónoma de Buenos Aires",
    capacity: 800,
    type: "club",
    contact: "info@thebow.com.ar",
    rating: 4,
  },
  {
    id: "14",
    nombre: "Stadium",
    location:
      "Victoria Ocampo Complejo La Normandina Loc. 4 Playa Grande, EAQ, B7602 Mar del Plata, Provincia de Buenos Aires",
    capacity: 1200,
    type: "club",
    contact: "info@stadium.com.ar",
    rating: 4,
  },
  {
    id: "15",
    nombre: "Gap",
    location: "Av. Constitución 5780, B7600 Mar del Plata, Provincia de Buenos Aires",
    capacity: 900,
    type: "club",
    contact: "info@gap.com.ar",
    rating: 4,
  },
  {
    id: "16",
    nombre: "Native Beach Club",
    location: "P438+VH, Campana, Ciudad Autónoma de Buenos Aires",
    capacity: 600,
    type: "outdoor",
    contact: "info@nativebeach.com.ar",
    rating: 4,
  },
  {
    id: "17",
    nombre: "Estancia Shibumi",
    location: "RP6 Kilometro 74, B1864 San Vicente, Provincia de Buenos Aires",
    capacity: 500,
    type: "outdoor",
    contact: "info@shibumi.com.ar",
    rating: 4,
  },
  {
    id: "18",
    nombre: "Mendoza",
    location: "Ozamis 1040, Maipú, Mendoza",
    capacity: 1000,
    type: "club",
    contact: "info@mendoza.com.ar",
    rating: 4,
  },
  {
    id: "19",
    nombre: "Montevideo",
    location: "Río Branco 1627, 11100 Montevideo, Departamento de Montevideo, Uruguay",
    capacity: 1200,
    type: "club",
    contact: "info@montevideo.com.uy",
    rating: 4,
  },
]

// PROVEEDORES ESENCIALES ACTUALIZADOS - SEGÚN LISTA PROPORCIONADA
const initialProviders: Provider[] = [
  // ARTE
  {
    id: "arte-1",
    name: "Dirección de artistas",
    category: "ARTE",
    contact: "direccion@artistas.com",
    rating: 5,
    services: ["Dirección artística", "Coordinación de shows"],
    priceRange: "$$$",
    item: "Dirección de artistas",
  },
  {
    id: "arte-2",
    name: "Actores + Serpiente",
    category: "ARTE",
    contact: "actores@serpiente.com",
    rating: 4,
    services: ["Performance", "Show con animales"],
    priceRange: "$$",
    item: "Actores + Serpiente",
  },
  {
    id: "arte-3",
    name: "Escenografía Pro",
    category: "ARTE",
    contact: "info@escenografiapro.com",
    rating: 5,
    services: ["Diseño escenográfico", "Montaje"],
    priceRange: "$$$",
    item: "Escenografía",
  },
  {
    id: "arte-4",
    name: "VJ Master",
    category: "ARTE",
    contact: "vj@master.com",
    rating: 5,
    services: ["Video jockey", "Visuales en vivo"],
    priceRange: "$$$",
    item: "VJ",
  },
  {
    id: "arte-5",
    name: "FX Specialists",
    category: "ARTE",
    contact: "fx@specialists.com",
    rating: 4,
    services: ["Efectos especiales", "Pirotecnia"],
    priceRange: "$$",
    item: "Fx",
  },
  {
    id: "arte-6",
    name: "Iluminación Total",
    category: "ARTE",
    contact: "luz@total.com",
    rating: 5,
    services: ["Diseño de iluminación", "Operación"],
    priceRange: "$$$",
    item: "Iluminador",
  },
  {
    id: "arte-7",
    name: "Asistente Luces",
    category: "ARTE",
    contact: "asistente@luces.com",
    rating: 4,
    services: ["Asistencia técnica", "Montaje luces"],
    priceRange: "$",
    item: "Asistente de Iluminación",
  },
  {
    id: "arte-8",
    name: "Glitter Dreams",
    category: "ARTE",
    contact: "glitter@dreams.com",
    rating: 4,
    services: ["Maquillaje con glitter", "Body painting"],
    priceRange: "$$",
    item: "Glitter",
  },
  {
    id: "arte-9",
    name: "Hair Stylists",
    category: "ARTE",
    contact: "hair@stylists.com",
    rating: 4,
    services: ["Peinados", "Styling"],
    priceRange: "$$",
    item: "Peinados",
  },
  {
    id: "arte-10",
    name: "Tattoo Artists",
    category: "ARTE",
    contact: "tattoo@artists.com",
    rating: 4,
    services: ["Tatuajes temporales", "Body art"],
    priceRange: "$$",
    item: "Tattoo",
  },
  {
    id: "arte-11",
    name: "Makeup Pro",
    category: "ARTE",
    contact: "makeup@pro.com",
    rating: 5,
    services: ["Maquillaje profesional", "Caracterización"],
    priceRange: "$$",
    item: "Maquillaje",
  },
  {
    id: "arte-12",
    name: "Pochoclos Gourmet",
    category: "ARTE",
    contact: "pochoclos@gourmet.com",
    rating: 3,
    services: ["Pochoclos", "Snacks"],
    priceRange: "$",
    item: "Pochoclos",
  },

  // BOOKING
  {
    id: "booking-1",
    name: "DJ Elite",
    category: "BOOKING",
    contact: "dj@elite.com",
    rating: 5,
    services: ["DJ", "Música en vivo"],
    priceRange: "$$$",
    item: "DJ",
  },
  {
    id: "booking-2",
    name: "Asistentes Pro",
    category: "BOOKING",
    contact: "asistentes@pro.com",
    rating: 4,
    services: ["Asistencia general", "Coordinación"],
    priceRange: "$$",
    item: "Asistentes",
  },
  {
    id: "booking-3",
    name: "Pre-Producción Team",
    category: "BOOKING",
    contact: "preproduccion@team.com",
    rating: 5,
    services: ["Pre-producción", "Planificación"],
    priceRange: "$$$",
    item: "Asistente de Pre-Producción",
  },
  {
    id: "booking-4",
    name: "Sound Engineer",
    category: "BOOKING",
    contact: "sound@engineer.com",
    rating: 5,
    services: ["Sonido", "Mezcla en vivo"],
    priceRange: "$$$",
    item: "Sonidista",
  },
  {
    id: "booking-5",
    name: "Ticket Control",
    category: "BOOKING",
    contact: "ticket@control.com",
    rating: 4,
    services: ["Control de boletos", "Acceso"],
    priceRange: "$",
    item: "Boletero",
  },
  {
    id: "booking-6",
    name: "QR Validators",
    category: "BOOKING",
    contact: "qr@validators.com",
    rating: 4,
    services: ["Validación QR", "Control digital"],
    priceRange: "$$",
    item: "Validadores QR",
  },

  // MARKETING
  {
    id: "marketing-1",
    name: "Content Creator",
    category: "MARKETING",
    contact: "content@creator.com",
    rating: 5,
    services: ["Creación de contenido", "Redes sociales"],
    priceRange: "$$$",
    item: "Creadora de contenido",
  },
  {
    id: "marketing-2",
    name: "Film Production",
    category: "MARKETING",
    contact: "film@production.com",
    rating: 5,
    services: ["Filmación", "Edición"],
    priceRange: "$$$",
    item: "Filmaker",
  },
  {
    id: "marketing-3",
    name: "Photo Studio",
    category: "MARKETING",
    contact: "photo@studio.com",
    rating: 4,
    services: ["Fotografía", "Retoque"],
    priceRange: "$$",
    item: "Fotografia",
  },
  {
    id: "marketing-4",
    name: "Merch Store",
    category: "MARKETING",
    contact: "merch@store.com",
    rating: 4,
    services: ["Merchandising", "Productos"],
    priceRange: "$$",
    item: "Merch",
  },
]

// TAREAS COMPLETAS - SOLO MANUALES (AUTOMÁTICAS DESDE 15 AGOSTO EN ADELANTE)
const initialTasks: Task[] = [
  // Tareas manuales existentes
  {
    id: "1",
    title: "Confirmar lineup AMK Halloween",
    description: "Contactar artistas y confirmar horarios",
    status: "in-progress",
    priority: "high",
    assignee: "Franco",
    dueDate: "2025-10-15",
    eventId: "event-2025-11-01-amk",
    category: "Producción",
    isAutomated: false,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "2",
    title: "Contratar seguridad Forest Dan",
    description: "Coordinar equipo de seguridad para el evento",
    status: "pending",
    priority: "medium",
    assignee: "Equipo",
    dueDate: "2025-07-30",
    eventId: "event-2025-07-09",
    category: "Logística",
    isAutomated: false,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "3",
    title: "Proporcionar Direcciones Faltantes",
    description: "Completar direcciones de venues que faltan información",
    status: "pending",
    priority: "medium",
    assignee: "Franco",
    dueDate: "2025-01-20",
    category: "Venues",
    isAutomated: false,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "4",
    title: "Verificar Venues Actualizados",
    description: "Revisar y actualizar información de contacto de venues",
    status: "pending",
    priority: "low",
    assignee: "Equipo",
    dueDate: "2025-01-25",
    category: "Venues",
    isAutomated: false,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "5",
    title: "Agregar Venues Internacionales",
    description: "Incluir información detallada de venues en Ecuador, Paraguay y Uruguay",
    status: "in-progress",
    priority: "medium",
    assignee: "Franco",
    dueDate: "2025-01-30",
    category: "Venues",
    isAutomated: false,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "6",
    title: "Revisar Eventos con Venues",
    description: "Verificar que todos los eventos tengan venue asignado correctamente",
    status: "pending",
    priority: "high",
    assignee: "Franco",
    dueDate: "2025-01-18",
    category: "Eventos",
    isAutomated: false,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "7",
    title: "Actualizar Capacidades",
    description: "Verificar y actualizar capacidades reales de todos los venues",
    status: "pending",
    priority: "low",
    assignee: "Equipo",
    dueDate: "2025-02-01",
    category: "Venues",
    isAutomated: false,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },

  // TAREAS AUTOMÁTICAS PARA EVENTOS DESDE 15 AGOSTO EN ADELANTE

  // MONTEVIDEO (17/08/2025)
  {
    id: "auto-montevideo-aug-pasajes-1723852800000",
    title: "🛫 Sacar Pasajes - Montevideo",
    description: "Reservar y confirmar pasajes para el evento en Montevideo. Faltan 214 días para el evento.",
    status: "pending",
    priority: "medium",
    assignee: "Franco",
    dueDate: "2025-01-22",
    eventId: "event-2025-08-17",
    category: "Logística",
    isAutomated: true,
    automatedTaskType: "pasajes",
    daysUntilEvent: 214,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "auto-montevideo-aug-hoteleria-1723852800000",
    title: "🏨 Hotelería - Montevideo",
    description: "Reservar alojamiento para el evento en Montevideo. Faltan 214 días para el evento.",
    status: "pending",
    priority: "medium",
    assignee: "Franco",
    dueDate: "2025-01-25",
    eventId: "event-2025-08-17",
    category: "Logística",
    isAutomated: true,
    automatedTaskType: "hoteleria",
    daysUntilEvent: 214,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "auto-montevideo-aug-aduana-ida-1723852800000",
    title: "📋 Aduana IDA - Uruguay",
    description: "Preparar documentación y trámites de aduana para ingreso a Uruguay. Faltan 214 días para el evento.",
    status: "pending",
    priority: "medium",
    assignee: "Franco",
    dueDate: "2025-01-29",
    eventId: "event-2025-08-17",
    category: "Documentación",
    isAutomated: true,
    automatedTaskType: "aduana_ida",
    daysUntilEvent: 214,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "auto-montevideo-aug-aduana-vuelta-1723852800000",
    title: "📋 Aduana VUELTA - Uruguay",
    description: "Preparar documentación y trámites de aduana para salida de Uruguay. Faltan 214 días para el evento.",
    status: "pending",
    priority: "low",
    assignee: "Franco",
    dueDate: "2025-02-05",
    eventId: "event-2025-08-17",
    category: "Documentación",
    isAutomated: true,
    automatedTaskType: "aduana_vuelta",
    daysUntilEvent: 214,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
]

const initialContracts: Contract[] = [
  {
    id: "1",
    type: "bailarin",
    name: "María González",
    email: "maria@email.com",
    phone: "+54 11 1234-5678",
    rate: 15000,
    status: "active",
    startDate: "2025-01-01",
    skills: ["Danza contemporánea", "Ballet", "Jazz"],
    eventIds: ["event-2025-11-01-amk", "event-2025-07-09"],
    providerName: "María González",
    contractorName: "DER Productions",
    amount: 15000,
    date: "2025-01-01",
  },
  {
    id: "2",
    type: "tecnico",
    name: "Carlos Rodríguez",
    email: "carlos@email.com",
    phone: "+54 11 8765-4321",
    rate: 12000,
    status: "active",
    startDate: "2025-01-01",
    skills: ["Sonido", "Iluminación", "Montaje"],
    eventIds: ["event-2025-11-01-amk"],
    providerName: "Carlos Rodríguez",
    contractorName: "DER Productions",
    amount: 12000,
    date: "2025-01-01",
  },
]

const initialBudgetItems: BudgetItem[] = [
  {
    id: "1",
    area: "ARTE",
    item: "Sistema de sonido principal",
    cantidad: 1,
    precioUnitario: 25000,
    precioTotal: 25000,
    resultadoNegociacion: 23000,
    desviacion: -2000,
    status: "paid",
    vendor: "Sonido Pro",
    eventId: "event-2025-11-01-amk",
  },
  {
    id: "2",
    area: "BOOKING",
    item: "Decoración temática Halloween",
    cantidad: 1,
    precioUnitario: 15000,
    precioTotal: 15000,
    resultadoNegociacion: 15000,
    desviacion: 0,
    status: "approved",
    vendor: "Deco Events",
    eventId: "event-2025-11-01-amk",
  },
]

const initialChatMessages: ChatMessage[] = [
  {
    id: "1",
    content: "Necesitamos confirmar el lineup para Halloween",
    message: "Necesitamos confirmar el lineup para Halloween",
    sender: "Franco",
    timestamp: "2025-01-15T10:00:00Z",
    type: "text",
    eventId: "event-2025-11-01-amk",
  },
]

const initialChats: Chat[] = [
  {
    id: "1",
    name: "AMK Halloween - Producción",
    participants: ["Franco", "Equipo Producción"],
    messages: initialChatMessages,
    lastMessage: "Necesitamos confirmar el lineup para Halloween",
    lastActivity: "2025-01-15T10:00:00Z",
    eventId: "event-2025-11-01-amk",
  },
]

export const useUnifiedEventStore = create<UnifiedEventStore>()(
  persist(
    (set, get) => ({
      // Initial state
      events: eventosCompletos2025,
      venues: initialVenues,
      providers: initialProviders,
      tasks: initialTasks,
      contracts: initialContracts,
      budgetItems: initialBudgetItems,
      chats: initialChats,
      chatMessages: initialChatMessages,

      // Event actions
      addEvent: (event) =>
        set((state) => ({
          events: [...state.events, event],
        })),

      updateEvent: (id, eventUpdate) =>
        set((state) => ({
          events: state.events.map((event) => (event.id === id ? { ...event, ...eventUpdate } : event)),
        })),

      deleteEvent: (id) =>
        set((state) => ({
          events: state.events.filter((event) => event.id !== id),
        })),

      getEvent: (id) => get().events.find((event) => event.id === id),

      // Venue actions
      addVenue: (venue) =>
        set((state) => ({
          venues: [...state.venues, venue],
        })),

      updateVenue: (id, venueUpdate) =>
        set((state) => ({
          venues: state.venues.map((venue) => (venue.id === id ? { ...venue, ...venueUpdate } : venue)),
        })),

      deleteVenue: (id) =>
        set((state) => ({
          venues: state.venues.filter((venue) => venue.id !== id),
        })),

      getVenue: (id) => get().venues.find((venue) => venue.id === id),

      // Provider actions
      addProvider: (providerData) => {
        const id = `provider-${Date.now()}`
        const newProvider: Provider = {
          id,
          name: providerData.name || "",
          category: providerData.category || "ARTE",
          contact: providerData.contact || "",
          rating: providerData.rating || 0,
          services: providerData.services || [],
          priceRange: providerData.priceRange || "$$",
          item: providerData.item || "",
          price: providerData.price || "",
          paymentMethod: providerData.paymentMethod || "Transferencia",
          status: providerData.status || "Disponibilidad",
          staff: providerData.staff || "",
          insurance: providerData.insurance || "",
          deadline: providerData.deadline || "",
          observations: providerData.observations || "",
          blocked: false,
          blockReason: "",
        }

        set((state) => ({
          providers: [...state.providers, newProvider],
        }))
      },

      updateProvider: (id, providerUpdate) =>
        set((state) => ({
          providers: state.providers.map((provider) =>
            provider.id === id ? { ...provider, ...providerUpdate } : provider,
          ),
        })),

      deleteProvider: (id) => {
        const provider = get().providers.find((p) => p.id === id)
        set((state) => ({
          providers: state.providers.filter((provider) => provider.id !== id),
        }))
        return provider
      },

      getProvider: (id) => get().providers.find((provider) => provider.id === id),

      rateProvider: (id, rating) =>
        set((state) => ({
          providers: state.providers.map((provider) => (provider.id === id ? { ...provider, rating } : provider)),
        })),

      blockProvider: (id, reason) =>
        set((state) => ({
          providers: state.providers.map((provider) =>
            provider.id === id ? { ...provider, blocked: true, blockReason: reason } : provider,
          ),
        })),

      // Task actions
      addTask: (task) =>
        set((state) => ({
          tasks: [...state.tasks, task],
        })),

      updateTask: (id, taskUpdate) =>
        set((state) => ({
          tasks: state.tasks.map((task) => (task.id === id ? { ...task, ...taskUpdate } : task)),
        })),

      deleteTask: (id) =>
        set((state) => ({
          tasks: state.tasks.filter((task) => task.id !== id),
        })),

      getTask: (id) => get().tasks.find((task) => task.id === id),

      // Contract actions
      addContract: (contract) =>
        set((state) => ({
          contracts: [...state.contracts, contract],
        })),

      updateContract: (id, contractUpdate) =>
        set((state) => ({
          contracts: state.contracts.map((contract) =>
            contract.id === id ? { ...contract, ...contractUpdate } : contract,
          ),
        })),

      deleteContract: (id) =>
        set((state) => ({
          contracts: state.contracts.filter((contract) => contract.id !== id),
        })),

      getContract: (id) => get().contracts.find((contract) => contract.id === id),

      // Budget actions
      addBudgetItem: (item) =>
        set((state) => ({
          budgetItems: [...state.budgetItems, item],
        })),

      updateBudgetItem: (id, itemUpdate) =>
        set((state) => ({
          budgetItems: state.budgetItems.map((item) => (item.id === id ? { ...item, ...itemUpdate } : item)),
        })),

      deleteBudgetItem: (id) =>
        set((state) => ({
          budgetItems: state.budgetItems.filter((item) => item.id !== id),
        })),

      getBudgetItem: (id) => get().budgetItems.find((item) => item.id === id),

      // Chat actions
      addChat: (chat) =>
        set((state) => ({
          chats: [...state.chats, chat],
        })),

      updateChat: (id, chatUpdate) =>
        set((state) => ({
          chats: state.chats.map((chat) => (chat.id === id ? { ...chat, ...chatUpdate } : chat)),
        })),

      deleteChat: (id) =>
        set((state) => ({
          chats: state.chats.filter((chat) => chat.id !== id),
        })),

      getChat: (id) => get().chats.find((chat) => chat.id === id),

      addMessage: (chatId, message) =>
        set((state) => ({
          chats: state.chats.map((chat) =>
            chat.id === chatId
              ? {
                  ...chat,
                  messages: [...chat.messages, message],
                  lastMessage: message.content,
                  lastActivity: message.timestamp,
                }
              : chat,
          ),
          chatMessages: [...state.chatMessages, message],
        })),
    }),
    {
      name: "unified-event-storage",
      version: 9,
      migrate: (persistedState: any, version: number) => {
        // Handle migration from previous versions
        if (version < 9) {
          return {
            ...persistedState,
            events: eventosCompletos2025,
            venues: initialVenues,
            providers: initialProviders,
            tasks: initialTasks,
            contracts: initialContracts,
            budgetItems: initialBudgetItems,
            chats: initialChats,
            chatMessages: initialChatMessages,
          }
        }

        return persistedState
      },
    },
  ),
)
